name: lcov-action
description: Generate and upload coverage.info
inputs:
  docker:
    description: "docker image to run in (default: none)"
    required: false
  workdir:
    description: "Working directory to run lcov on (default: current dir)"
    required: false
  lcov_capture_args:
    description: "Additional arguments to pass to lcov capture"
    required: false
  output:
    description: "Desired output file location (default: workdir/coverage.info)"
    required: false
  ignore:
    description: List of glob patterns describing files to ignore
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: $GITHUB_ACTION_PATH/action.sh "${{ inputs.docker }}" "${{ inputs.workdir }}" "${{ inputs.output }}" ${{ inputs.ignore }}
      env:
        LCOV_CAPTURE_ARGS: ${{ inputs.lcov_capture_args }}
